backend:
  name: git-gateway
  branch: master
media_folder: "public/assets/images"
public_folder: "/assets/images"
publish_mode: editorial_workflow
collections:
  - label: "Projects" 
    name: "project"
    folder: "src/projects" 
    create: true 
    slug: "{{year}}-{{month}}-{{slug}}"
    preview_path: projects/{{slug}}
    fields: 
     - { label: "Title", name: "title", widget: "string" }
     - { label: "Date", name: "date", widget: "datetime" }
     - label: "Tags"
       name: "tags"
       widget: "select"
       multiple: true
       options: ["project", "featured"]
       default: ["project"]
     - { label: "Featured Image", name: "image", widget: "image" }
     - { label: "Image caption", name: "imageAlt", widget: "string" }
     - { label: "Summary", name: "summary", widget: "string" }
     - { label: "Page Meta Description", name: "metaDescription", widget: "string" }
     - { label: "Body", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "index"
        file: "src/index.json"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Page Meta Desciption", name: "metaDescription", widget: "string" }
          - { label: "Introduction", name: "intro", widget: "string" }
          - { label: "Summary", name: "summary", widget: "string" }
      - label: "Work Page"
        name: "work"
        file: "src/work/work.json"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Page Meta Desciption", name: "metaDescription", widget: "string" }
      - label: "About Page"
        name: "about"
        file: "src/about/about.json"
        preview_path: about/
        fields: 
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Summary", name: "summary", widget: "string" }
          - { label: "Landing Image", name: "landingImage", widget: "image" }
          - { label: "Landing image desciption", name: "landingImageAlt", widget: "string" }
          - { label: "Page meta description", name: "metaDescription", widget: "string" }
          - label: "Links" 
            name: "links" 
            widget: "list"
            collapsed: true
            fields: 
              - { label: "Name", name: "linkName", widget: "string" }
              - { label: "url", name: "url", widget: "string" }
          - label: "Skills"
            name: "skills"
            widget: "list"
            collapsed: true
            fields: 
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Image description", name: "imageAlt", widget: "string" }
          - label : "Interests"
            name: "interests"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Item", name: "item", widget: "string"}
          - label: "InterestsImage"
            name: "interestsImage"
            collapsed: true
            widget: "image"
          - { label: "Body", name: "body", widget: "markdown"}
      - label: "Contact Page"
        name: "contact"
        file: "src/contact/contact.json"
        editor:
          preview: false
        fields: 
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Page meta description", name: "metaDescription", widget: "string" }
  - label: "General"
    name: "general"
    files:
      - label: "Header"
        name: "header"
        file: "src/_data/global.json"
        editor:
          preview: false
        fields:
          - { label: "Logo", name: "logo", widget: "image", choose_url: false, comment: "Use .svg files for your logos." }
      - label: "Footer"
        name: "footer"
        file: "src/_data/global.json"
        editor:
          preview: false
        fields: 
          - label: "Social Links" 
            name: "socialLinks" 
            widget: "list"
            collapsed: true
            fields: 
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Url", name: "url", widget: "string" }
              - { label: "Icon", name: "img", widget: "image" }
              - { label: "Icon Alt", name: "imgAlt", widget: "string" }