backend:
  name: git-gateway
  branch: master
media_folder: "public/assets/images"
public_folder: "/assets/images"
collections:
  - name: "project" 
    label: "Project"
    folder: "src/projects" 
    create: true 
    slug: "{{year}}-{{month}}-{{slug}}" 
    fields: 
     - { label: "Title", name: "title", widget: "string" }
     - { label: "Date", name: "date", widget: "datetime" }
     - { label: "Tags", name: "tags", widget: "select", multiple: true, options: ["project, featured"], default: ["project"] }
     - { label: "Featured Image", name: "image", widget: "image" }
     - { label: "Image caption", name: "imageAlt", widget: "string" }
     - { label: "Summary", name: "summary", widget: "string" }
     - { label: "Page Meta Description", name: "metaDescription", widget: "string" }
     - { label: "Body", name: "body", widget: "markdown"}
  - name : "about"
    label: "About"
    folder: "src/about"
    create: false
    delete: false
    slug: "{{ title }}"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Landing Image", name: "landingImage", widget: "image" }
      - { label: "Landing image desciption", name: "landingImageAlt", widget: "string" }
      - { label: "Page meta description", name: "metaDescription", widget: "string" }
      - label: "Links" 
        name: "links" 
        widget: "list"
        collapsed: true
        fields: 
          - { label: "Name", name: "linkName", widget: "string" }
          - { label: "url", name: "url", widget: "string" }
      - label: "Skills"
        name: "skills"
        widget: "list"
        collapsed: true
        fields: 
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Image description", name: "imageAlt", widget: "string" }
      - label : "Interests"
        name: "interests"
        widget: "list"
        collapsed: true
        fields:
          - { label: "Item", name: "item", widget: "string"}
      - label: "InterestsImage"
        name: "interestsImage"
        collapsed: true
        widget: "image"
      - { label: "Body", name: "body", widget: "markdown"}