backend:
  name: git-gateway
  branch: master
media_folder: "public/assets/images"
public_folder: "/assets/images"
publish_mode: editorial_workflow
collections:
  - label: "Projects" 
    name: "project"
    folder: "src/projects" 
    create: true 
    slug: "{{year}}-{{month}}-{{slug}}"
    preview_path: projects/{{slug}}
    fields: 
     - { label: "Title", name: "title", widget: "string" }
     - { label: "Date", name: "date", widget: "datetime" }
     - label: "Tags"
       name: "tags"
       widget: "select"
       multiple: true
       options: ["project", "featured"]
       default: ["project"]
     - { label: "Thumbnail Image", name: "image", widget: "image" }
     - { label: "Image caption", name: "imageAlt", widget: "string" }
     - { label: "Summary", name: "summary", widget: "string" }
     - { label: "Page Meta Description", name: "metaDescription", widget: "string" }
     - { label: "Body", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "index"
        file: "src/index.json"
        preview_path: /
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Page Meta Desciption", name: "metaDescription", widget: "string" }
          - { label: "Introduction", name: "intro", widget: "string", hint: "The first line a user see's when visiting the website." }
          - { label: "Summary", name: "summary", widget: "string", hint: "Try keep it short but effective." }
      - label: "Work Page"
        name: "work"
        file: "src/work/work.json"
        preview_path: work/
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Page Meta Desciption", name: "metaDescription", widget: "string" }
          - label: "Pagination"
            name: "pagination"
            widget: "object"
            fields:
              - { label: "Size", name: "size", required: false, widget: "number", value_type: "int", hint: "The amount of projects you want displayed at a time." }
              - { label: "Reverse Order", required: false, name: "reverse", widget: "boolean", default: true, hint: "Reversing Order displays latest to oldest." }
      - label: "About Page"
        name: "about"
        file: "src/about/about.json"
        preview_path: about/
        fields: 
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Summary", name: "summary", widget: "string" }
          - { label: "Landing Image", name: "landingImage", widget: "image", hint: "This image will be the landing image for about." }
          - { label: "Landing image desciption", name: "landingImageAlt", widget: "string" }
          - { label: "Page meta description", name: "metaDescription", widget: "string" }
          - label: "Links" 
            name: "links" 
            widget: "list"
            collapsed: true
            hint: "Links to other places e.g. (LinkedIn, Behance, etc.)"
            required: false
            fields: 
              - { label: "Name", name: "linkName", widget: "string", hint: "Name of the link you want displayed." }
              - { label: "url", name: "url", widget: "string" }
          - label: "Skills"
            name: "skills"
            widget: "list"
            collapsed: true
            fields: 
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Image description", name: "imageAlt", widget: "string" }
          - label : "Interests"
            name: "interests"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Item", name: "item", widget: "string"}
          - label: "InterestsImage"
            name: "interestsImage"
            collapsed: true
            widget: "image"
          - { label: "Body", name: "body", widget: "markdown"}
      - label: "Contact Page"
        name: "contact"
        file: "src/contact/contact.json"
        preview_path: contact/
        editor:
          preview: false
        fields: 
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Page meta description", name: "metaDescription", widget: "string" }
  - label: "General"
    name: "general"
    files:
      - label: "Header & Footer"
        name: "headerFooter"
        file: "src/_data/global.json"
        preview_path: /
        editor:
          preview: false
        fields:
          - { label: "Logo", name: "logo", widget: "image", collapsed: true, hint: "The logo displayed in the navigation bar." }
          - label: "Social Links" 
            name: "socialLinks" 
            widget: "list"
            collapsed: true
            hint: "Links displayed at the bottom of the footer under 'Follow Me'."
            fields: 
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Url", name: "url", widget: "string" }
              - { label: "Icon", name: "img", widget: "image", hint: "Using .svg files are best for icons." }
              - { label: "Icon Alt", name: "imgAlt", widget: "string" }