backend:
  name: git-gateway
  branch: master
media_folder: "public/assets/images"
public_folder: "/assets/images"
collections:
  - name: "project" 
    label: "Project"
    folder: "src/projects" 
    create: true 
    slug: "{{year}}-{{month}}-{{slug}}" 
    fields: 
     - { label: "Title", name: "title", widget: "string" }
     - { label: "Date", name: "date", widget: "datetime" }
     - { label: "Tags", name: "tags", widget: "select", multiple: true, options: ["project, featured"], default: ["project"] }
     - { label: "Featured Image", name: "image", widget: "image" }
     - { label: "Image caption", name: "imageAlt", widget: "string" }
     - { label: "Summary", name: "summary", widget: "string" }
     - { label: "Page Meta Description", name: "metaDescription", widget: "string" }
     - { label: "Body", name: "body", widget: "markdown"}